[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_VERSION = "1.0.0"
  SECRETS_SCAN_OMIT_PATHS = "static/js/**"
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_OPENAI_API_KEY"
